local debugdraw = require("modules.debug-draw")

function init(self)
    msg.post(".", "acquire_input_focus")
    msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function on_input(self, action_id, action)
    if action_id == hash("touch") and action.pressed then
        print("Touch!")
    end
end

function update(self, dt)
    debugdraw.line(100, 108, 150, 150, debugdraw.COLORS.green)
    debugdraw.text("Debug!", 100, 200, debugdraw.COLORS.green)
end
